# Generated by Django 4.2.30 on 2026-05-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='tile',
            new_name='title',
        ),
    ]
