# Generated by Django 4.2.30 on 2026-05-04 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_tile_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='posted_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
